### ISSUE TITLE
example.py not working

### ISSUE THREAD

**Issue by bmorris3** [rodluger/para#1]
When I run `example.py` I get the following error: 

```
bash-4.1$ python example.py 
Traceback (most recent call last):
  File "example.py", line 46, in <module>
    for res in para.map(quadratic, np.arange(50), args = (1, 1, 1), kwargs = {}):
  File "/astro/users/bmmorris/git/para/para/wrappers.py", line 86, in map
    return multi(f, x, args = args, kwargs = kwargs, method = 'map', **pool_kwargs)
  File "/astro/users/bmmorris/git/para/para/wrappers.py", line 52, in multi
    return getattr(pool, method)(w, x)
  File "/astro/users/bmmorris/miniconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/astro/users/bmmorris/miniconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: quadratic() takes exactly 4 arguments (3 given)
```

**Comment by bmorris3** [comment]
I'm not sure what fixed it, but the recent commits have made this error go away. 

Thanks!

**Comment by bmorris3** [comment]
Although before forgetting about this issue, I'd recommend simply printing a notice to the user to add `para` to their path, so that they will know if it's been added to their `.cshrc` or `.bashrc`. Typically it's good form not to touch people's `rc` files and to let them sort it out (hopefully) intelligently.
